CREATE TABLE MEMBER (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  ACCOUNT VARCHAR(13) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT null ON UPDATE CURRENT_TIMESTAMP
)