spring:
  cloud:
    gateway:
      routes:
        - id: post_service
          uri: http://localhost:10000
          predicates:
            - Path=/posts/**
          filters:
            - name: PostServiceFilterFactory
              args:
